/*

 * This Java source file was generated by the Gradle 'init' task.
 */
package no.s11.wpsld.impl;

import static org.junit.Assert.*;

import java.io.IOException;
import java.nio.file.Files;

import org.junit.Test;

import no.s11.wpsld.WPSLD;
import no.s11.wpsld.WPSLDPath;

public class TestWPSLD {
    @Test 
    public void newRootIsDirectory() throws IOException {
    	WPSLD wpsld = WPSLD.Factory.create();
        WPSLDPath root = wpsld.newRoot();
        assertTrue("New root should be a directory", 
        		Files.isDirectory(root.getPath()));
    }
}
