/*

 * This Java source file was generated by the Gradle 'init' task.
 */
package no.s11.wpsld.impl;

import static org.junit.Assert.assertTrue;

import java.io.IOException;
import java.nio.file.Files;

import org.junit.Test;

import no.s11.wpsld.WPSLDPath;
import no.s11.wpsld.path.BaseName;

public class TestTemporaryRoot {
    @Test 
    public void newRootIsDirectory() throws IOException {
    	WPSLDPath root = new TemporaryRoot();
        assertTrue("Temporary root should be a directory: " + root, 
        		Files.isDirectory(root.getPath()));
        assertTrue("Basename should start with wpsld: " + root, 
        		new BaseName(root.getPath()).toString().startsWith("wpsld")); 
    }
}
